title: Barsnes
email: tobias@barsnes.co
description: >- # this means to ignore newlines until "baseurl:"

permalink: /:categories/:year/:month/:title:output_ext

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://barsnes.co" # the base hostname & protocol for your site, e.g. http://example.com

include: [_assets, .htcaccess]

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  images:
    output: false
  posts:
    output: true
  projects:
    output: true
    permalink: /:collection/:year/:title

defaults:
  -
    scope:
      path:            "admin"
    values:
      sitemap:         false

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true
  quality: 75
  img_dir: ["/_assets/images"]
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  gifs: [".gif"]
  regenerate: false
  webp_path: nil
  exclude: []
