backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: Barsnes/Barsnes_Portfolio

media_folder: "_assets/images/" # Media files will be stored in the repo under images/uploads

collections:
  - name: "image" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Portfolio Images" # Used in the UI, ie.: "New Post"
    folder: "_images" # The path to the folder where the documents are stored
    sort: "date:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Image", name: "imageurl", widget: "image", tagname: "img"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
